#!/usr/bin/bash

#get the first octets of the network ip
ifconfig | grep "broadcast" | cut -d " " -f 10 | cut -d "." -f 1,2,3 | uniq > octets.txt

#Set variable to have the value of octets.txt
OCTETS=$(cat octets.txt)

#Create a new .txt
echo "" > $OCTETS.txt

#Loop
for ip in {1..254}
do 
	ping -c 1 $OCTETS.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" >> $OCTETS.txt
done 

cat $OCTETS.txt

